[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "logtracing"
version = "0.0.1"
authors = [
  { name="Rene Barrera", email="rene.barrera1022@gmail.com" },
]
description = "Package to track exceptions in applications."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/logtracing/python-pkg"
"Bug Tracker" = "https://github.com/logtracing/python-pkg/issues"
